# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbA5LK7GxRAOeVtd6OkGXkkjY1VzBun4
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df = load_data()

# 查看前10行数据
st.dataframe(df.head(10))


st.set_page_config(page_title="Amazon Business Performance Dashboard", layout="wide")

@st.cache_data
def load_data():
    # 读取新生成的干净数据
    df = pd.read_csv("amazon_clean.csv", encoding="utf-8-sig")

    # 去掉 % 符号，转换数字
    df['discount_percentage'] = df['discount_percentage'].str.replace('%', '', regex=False).astype(float)

    # 计算 estimated_sales
    df['estimated_sales'] = df['rating_count'] * df['discounted_price']

    # 提取主类别
    df['main_category'] = df['category'].apply(lambda x: str(x).split('|')[0])

    return df

df = load_data()

# ---------------- KPI 计算 ----------------
average_discount = df['discount_percentage'].mean()
average_rating = df['rating'].mean()
total_reviews = df['rating_count'].sum()
total_sales = df['estimated_sales'].sum()

st.title("📊 Amazon Business Performance Dashboard")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Average Discount (%)", f"{average_discount:.2f}")
col2.metric("Average Rating", f"{average_rating:.2f}")
col3.metric("Total Review Count", f"{int(total_reviews):,}")
col4.metric("Estimated Total Sales (₹)", f"{total_sales:,.2f}")

st.markdown("---")

# ---------------- 可视化1：饼图（类别销售额分布） ----------------
sales_by_category = df.groupby('main_category')['estimated_sales'].sum().reset_index()
sales_by_category = sales_by_category[sales_by_category['estimated_sales'] > 0]

fig1 = px.pie(
    sales_by_category,
    names='main_category',
    values='estimated_sales',
    title='Sales Distribution by Main Category'
)
st.plotly_chart(fig1, use_container_width=True)

st.markdown("---")

# ---------------- 可视化2：散点图（折扣 vs 评分） ----------------
df_scatter = df.dropna(subset=['estimated_sales', 'rating', 'discount_percentage'])
df_scatter = df_scatter[(df_scatter['estimated_sales'] > 0) & (df_scatter['discount_percentage'] >= 20)]

fig2 = px.scatter(
    df_scatter,
    x='discount_percentage',
    y='rating',
    size='estimated_sales',
    size_max=20,
    title='Discount Percentage vs Rating (Discount ≥ 20%)',
    trendline='ols',
    hover_data=['product_name']
)
st.plotly_chart(fig2, use_container_width=True)

st.markdown("---")

# ---------------- 可视化3：柱状图（不同类别的平均评分） ----------------
category_rating = df.groupby('main_category')['rating'].mean().reset_index()
fig3 = px.bar(
    category_rating,
    x='main_category',
    y='rating',
    title='Average Rating by Main Category'
)
st.plotly_chart(fig3, use_container_width=True)