# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbA5LK7GxRAOeVtd6OkGXkkjY1VzBun4
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Amazon Business Performance Dashboard", layout="wide")

@st.cache_data
def load_data():
    # 加了 encoding，避免 csv 中文或符号乱码
    df = pd.read_csv("amazon.csv", encoding="utf-8-sig")

    # 数据清洗
    df['discounted_price'] = df['discounted_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False).astype(float)
    df['actual_price'] = df['actual_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False).astype(float)
    df['discount_percentage'] = df['discount_percentage'].str.replace('%', '', regex=False).astype(float)
    df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
    df['rating_count'] = df['rating_count'].str.replace(',', '', regex=False).astype(float)
    df['estimated_sales'] = df['rating_count'] * df['discounted_price']
    df['main_category'] = df['category'].apply(lambda x: str(x).split('|')[0])

    # 检查核心数据（方便你调试）
    st.write("🔎 Preview of cleaned data:", df[['main_category', 'estimated_sales', 'discount_percentage', 'rating']].head(10))

    return df

df = load_data()

average_discount = df['discount_percentage'].mean()
average_rating = df['rating'].mean()
total_reviews = df['rating_count'].sum()
total_sales = df['estimated_sales'].sum()

st.title("📊 Amazon Business Performance Dashboard")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Average Discount (%)", f"{average_discount:.2f}")
col2.metric("Average Rating", f"{average_rating:.2f}")
col3.metric("Total Review Count", f"{int(total_reviews):,}")
col4.metric("Estimated Total Sales (₹)", f"{total_sales:,.2f}")

st.markdown("---")

# ------------------ 可视化1：饼图 -------------------
sales_by_category = df.groupby('main_category')['estimated_sales'].sum().reset_index()

# 过滤掉销售额为0的类别，避免显示全11%（主要是这一步之前遗漏了）
sales_by_category = sales_by_category[sales_by_category['estimated_sales'] > 0]

fig1 = px.pie(
    sales_by_category,
    names='main_category',
    values='estimated_sales',
    title='Sales Distribution by Main Category'
)
st.plotly_chart(fig1, use_container_width=True)

st.markdown("---")

# ------------------ 可视化2：散点 -------------------
df_scatter = df.dropna(subset=['estimated_sales', 'rating', 'discount_percentage'])
df_scatter = df_scatter[(df_scatter['estimated_sales'] > 0) & (df_scatter['discount_percentage'] >= 20)]

fig2 = px.scatter(
    df_scatter,
    x='discount_percentage',
    y='rating',
    size='estimated_sales',
    size_max=20,
    title='Discount Percentage vs Rating (Discount ≥ 20%)',
    trendline='ols',
    hover_data=['product_name']
)
st.plotly_chart(fig2, use_container_width=True)

st.markdown("---")

# ------------------ 可视化3：类别平均评分 -------------------
category_rating = df.groupby('main_category')['rating'].mean().reset_index()
fig3 = px.bar(
    category_rating,
    x='main_category',
    y='rating',
    title='Average Rating by Main Category'
)
st.plotly_chart(fig3, use_container_width=True)